### ISSUE TITLE
zbundle don't use host resolve.conf

### ISSUE THREAD

**Issue by mohamedgalal99** [threefoldtech/0-bundle#2]
we are facing problem when running zbundle that it can't resolve domain names,

- /etc/resolv.conf don't read nameservers from host itself, instead it get nameservers when flist created 

{code}
root@cpu-02:~/.zbundle/capacity# cat etc/resolv.conf 
\# Generated by dhcpcd from eth0.dhcp
\# /etc/resolv.conf.head can replace this line
domain home.maxux.net
nameserver 10.241.0.254

{code}

**Comment by muhamadazmy** [comment]
It's fixed in code except the auto builder of the new binary doesn't seem to kick in. I reported this to Maxime but he in not working today.

**Comment by muhamadazmy** [comment]
New zbundle binary is out with the fix. Please give it a try
